/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internship-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InternshipPlacesController_findAll"];
        put?: never;
        post: operations["InternshipPlacesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internship-places/my-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's own reviews with the place each is about, newest first. Declared before :id. */
        get: operations["InternshipPlacesController_myReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internship-places/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provinces that already have places, most used first. Declared before :id. */
        get: operations["InternshipPlacesController_provinces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internship-places/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fields of work: the preset list, then the ones users added. Declared before :id. */
        get: operations["InternshipPlacesController_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internship-places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InternshipPlacesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["InternshipPlacesController_remove"];
        options?: never;
        head?: never;
        patch: operations["InternshipPlacesController_update"];
        trace?: never;
    };
    "/api/v1/internship-places/{placeId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PlaceReviewsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internship-places/{placeId}/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PlaceReviewsController_remove"];
        options?: never;
        head?: never;
        patch: operations["PlaceReviewsController_update"];
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where Core Hub sends the browser with a token. The answers follow the
         *     table of auth-contract 5.1, in its order:
         *
         *      - no `access_token`: 400.
         *      - no `state`: Core Hub started this sign-in itself, e.g. a sidebar click.
         *        The token is dropped unused and the browser restarts at /auth/login,
         *        which comes back here with a state this subsystem can check. A link
         *        carrying an attacker's token therefore signs the victim in as the
         *        victim, never as the attacker.
         *      - a `state` without a matching state cookie: 401, and no redirect - if
         *        the browser refuses cookies, redirecting again would loop forever. A
         *        browser gets a page with a "sign in again" link instead of raw JSON.
         *      - a token that fails the ten checks: 401 · a role this subsystem does
         *        not accept: 403.
         *      - otherwise the token becomes the session cookie and the browser goes
         *        to the page it started from.
         *
         *     No failure sets the session cookie. The URL carries the access token, so
         *     it is never logged - only the path.
         */
        get: operations["SsoController_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Starts a sign-in: mints a single-use state, keeps it (with the page to
         *     return to) in a cookie only the callback receives, and sends the browser
         *     to Core Hub's web app, which signs the user in or renews their session.
         *
         *     No callback_url is sent: Core Hub only ever redirects to the one in its
         *     registry, and refuses a different one with 400.
         */
        get: operations["SsoController_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signs out everywhere. Dropping only this subsystem's cookies would be
         *     undone by the next click, which Core Hub - still signed in - would answer
         *     with a fresh token. So the browser goes on to Core Hub's /logout, where
         *     the user confirms ending the Core Hub session.
         *
         *     Public on purpose: it must work with an expired or missing session, and
         *     all it does is clear this subsystem's own cookies.
         */
        post: operations["SsoController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePlaceDto: {
            /** @description Integer satang; 0 when the place pays no allowance. */
            dailyAllowanceSatang?: number;
            latitude: number;
            longitude: number;
            name: string;
            /** @description Things to watch out for and benefits. */
            notes: string;
            /** @description Thai province name, e.g. "เชียงใหม่" (the word "จังหวัด" is dropped). */
            province: string;
            tags?: string[];
            workHours?: string;
        };
        CreateReviewDto: {
            /** @description Optional - a score alone is a review too. An empty text is stored as no text. */
            comment?: string;
            /** @description Buddhist-era year; the service rejects a year after next year. */
            internshipYear?: number;
            /** @description Job title during the internship, e.g. "Frontend Developer Intern". */
            position?: string;
            score: number;
        };
        DeletedDto: {
            deleted: boolean;
            id: string;
        };
        MyReviewDto: {
            /** @description null when the reviewer gave a score only. */
            comment: string | null;
            /** Format: date-time */
            createdAt: string;
            id: string;
            /** @description Buddhist-era year of the internship. */
            internshipYear: number | null;
            /** @description Whether the caller wrote this review. */
            isMine: boolean;
            /** @description Reviewer's student or staff code - returned to staff (place-review:delete:any) only. */
            personCode?: string | null;
            placeId: string;
            placeName: string;
            /** @description Thai province name without the word "จังหวัด". */
            placeProvince: string;
            position: string | null;
            /** @description 1-5 stars. */
            score: number;
            /** Format: date-time */
            updatedAt: string;
        };
        PlaceDetailDto: {
            /** @description Average review score rounded to one decimal; 0 without reviews. */
            averageScore: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Daily allowance in satang; 0 = none. */
            dailyAllowanceSatang: number;
            /** @description From the university, or from nearLat/nearLng when the list was asked with them. */
            distanceKm: number;
            id: string;
            latitude: number;
            longitude: number;
            /** @description The caller's own review of this place, if any. */
            myReviewId: string | null;
            name: string;
            /** @description Things to watch out for and benefits. */
            notes: string;
            /** @description Thai province name without the word "จังหวัด". */
            province: string;
            /** @description Position in the ranking of the whole directory (1 = best). */
            rank: number;
            reviewCount: number;
            /** @description Newest first. */
            reviews: components["schemas"]["ReviewViewDto"][];
            /** @description Number of reviews per score. */
            scoreDistribution: components["schemas"]["ScoreDistributionDto"];
            /** @description Keys from GET /api/v1/internship-places/tags (preset keys or users' own words). */
            tags: string[];
            /** Format: date-time */
            updatedAt: string;
            workHours: string | null;
        };
        PlaceSummaryDto: {
            /** @description Average review score rounded to one decimal; 0 without reviews. */
            averageScore: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Daily allowance in satang; 0 = none. */
            dailyAllowanceSatang: number;
            /** @description From the university, or from nearLat/nearLng when the list was asked with them. */
            distanceKm: number;
            id: string;
            latitude: number;
            longitude: number;
            name: string;
            /** @description Things to watch out for and benefits. */
            notes: string;
            /** @description Thai province name without the word "จังหวัด". */
            province: string;
            /** @description Position in the ranking of the whole directory (1 = best). */
            rank: number;
            reviewCount: number;
            /** @description Keys from GET /api/v1/internship-places/tags (preset keys or users' own words). */
            tags: string[];
            /** Format: date-time */
            updatedAt: string;
            workHours: string | null;
        };
        PlaceTagDto: {
            /** @description Stored value: a preset key (`web`) or the words of a field users added. */
            key: string;
            /** @description Label shown on the page, e.g. `Web Development`. */
            label: string;
            /** @description Places listing this field of work. */
            placeCount: number;
            /** @description From the preset list (true) or added by users (false). */
            preset: boolean;
        };
        ProvinceDto: {
            /** @description Thai province name without the word "จังหวัด". */
            name: string;
            placeCount: number;
        };
        ReviewViewDto: {
            /** @description null when the reviewer gave a score only. */
            comment: string | null;
            /** Format: date-time */
            createdAt: string;
            id: string;
            /** @description Buddhist-era year of the internship. */
            internshipYear: number | null;
            /** @description Whether the caller wrote this review. */
            isMine: boolean;
            /** @description Reviewer's student or staff code - returned to staff (place-review:delete:any) only. */
            personCode?: string | null;
            position: string | null;
            /** @description 1-5 stars. */
            score: number;
            /** Format: date-time */
            updatedAt: string;
        };
        ScoreDistributionDto: {
            1: number;
            2: number;
            3: number;
            4: number;
            5: number;
        };
        UpdatePlaceDto: {
            dailyAllowanceSatang?: number;
            latitude?: number;
            longitude?: number;
            name?: string;
            notes?: string;
            province?: string;
            tags?: string[];
            workHours?: string;
        };
        UpdateReviewDto: {
            /** @description Optional - a score alone is a review too. An empty text is stored as no text. */
            comment?: string;
            /** @description Buddhist-era year; null clears it ("ไม่ระบุ"). */
            internshipYear?: number | null;
            position?: string;
            score?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InternshipPlacesController_findAll: {
        parameters: {
            query?: {
                /** @description Matches the name, province, notes, work hours and review comments. */
                q?: string;
                province?: string;
                allowance?: "paid" | "free";
                minRating?: number;
                /** @description A preset key (`web`) or the words of a field of work users added. */
                tag?: string;
                /** @description Ranking (default), average score, allowance, review count, distance, newest or name. */
                sort?: "rank" | "rating" | "allowance" | "reviews" | "distance" | "newest" | "name";
                /** @description Measure `distanceKm` from here instead of the university (both or neither). */
                nearLat?: number;
                nearLng?: number;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlaceSummaryDto"][];
                        meta?: {
                            limit: number;
                            page: number;
                            total: number;
                            totalPages: number;
                        };
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    InternshipPlacesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlaceDetailDto"];
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    InternshipPlacesController_myReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MyReviewDto"][];
                        meta?: {
                            limit: number;
                            page: number;
                            total: number;
                            totalPages: number;
                        };
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    InternshipPlacesController_provinces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProvinceDto"][];
                        meta?: {
                            limit: number;
                            page: number;
                            total: number;
                            totalPages: number;
                        };
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    InternshipPlacesController_tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlaceTagDto"][];
                        meta?: {
                            limit: number;
                            page: number;
                            total: number;
                            totalPages: number;
                        };
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    InternshipPlacesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlaceDetailDto"];
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    InternshipPlacesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeletedDto"];
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    InternshipPlacesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlaceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlaceDetailDto"];
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    PlaceReviewsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReviewViewDto"];
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    PlaceReviewsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeletedDto"];
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    PlaceReviewsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReviewViewDto"];
                        /** @enum {boolean} */
                        success: true;
                    };
                };
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoController_callback: {
        parameters: {
            query?: {
                access_token?: string;
                token_type?: "Bearer" | "bearer";
                expires_in?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
